name: Bug Report
description: Reporte um bug encontrado no sistema
title: "[BUG] "
labels: bug
assignees: []
body:
  - type: input
    attributes:
      label: Descrição
      description: Explique o bug encontrado.
      placeholder: "Ex.: Ao tentar logar, recebo erro 500"
  - type: textarea
    attributes:
      label: Passos para reproduzir
      description: Liste os passos detalhados
      placeholder: |
        1. Abra a página de login
        2. Insira usuário e senha
        3. Clique em entrar
  - type: textarea
    attributes:
      label: Resultado esperado
      description: O que você esperava que acontecesse
  - type: textarea
    attributes:
      label: Resultado atual
      description: O que acontece de fato
  - type: dropdown
    attributes:
      label: Área afetada
      options:
        - Backend
        - Frontend
        - Student
        - Instructor
        - Admin
      description: Selecione a área do bug
