name: Bug Report
description: Reporte um bug encontrado no sistema
title: "[BUG] "
labels: bug
assignees: 
body:
  - type: markdown
    attributes:
      value: |
        **Descrição**
        Explique o bug encontrado.
  - type: textarea
    attributes:
      label: Passos para reproduzir
      description: Liste os passos detalhados
      placeholder: 1. ...
      required: true
  - type: textarea
    attributes:
      label: Resultado esperado
      description: O que você esperava que acontecesse
      required: true
  - type: textarea
    attributes:
      label: Resultado atual
      description: O que acontece de fato
      required: true
  - type: dropdown
    attributes:
      label: Área afetada
      options:
        - Backend
        - Frontend
        - Fullstack
      description: Selecione a área do bug
      required: true
